spring.application.name=AIPromptLibraryManager


spring.datasource.url=jdbc:postgresql://localhost:5432/prompt_library
spring.datasource.username=postgres
spring.datasource.password=Germany2028


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.thymeleaf.cache=false
